<?php if($error):?><div class="alert alert-danger"><?=issueEscape($error)?></div><?php endif;?>
<?php if($voucher): $items=is_array($_POST['items']??null)?$_POST['items']:$voucher['items']; ?>
<div class="card border-0 shadow-sm"><div class="card-header bg-white d-flex justify-content-between"><strong>ویرایش حواله</strong><a class="btn btn-sm btn-secondary" href="view.php?id=<?=(int)$voucher['id']?>">بازگشت</a></div><div class="card-body">
<form method="post" id="f"><input type="hidden" name="id" value="<?=(int)$voucher['id']?>"><input type="hidden" name="csrf_token" value="<?=issueEscape(issueCsrfToken())?>"><div class="row g-3 mb-3">
<div class="col-md-4"><label>شماره حواله</label><input class="form-control" name="voucher_number" required value="<?=issueEscape($_POST['voucher_number']??$voucher['voucher_number'])?>"></div><div class="col-md-4"><label>تاریخ</label><input type="datetime-local" class="form-control" name="voucher_date" required value="<?=issueEscape($_POST['voucher_date']??date('Y-m-d\TH:i',strtotime($voucher['voucher_date'])))?>"></div><div class="col-md-4"><label>انبار</label><select class="form-select" name="warehouse_id" id="warehouse_id" required><?php $sw=(int)($_POST['warehouse_id']??$voucher['warehouse_id']);foreach($warehouses as $w):?><option value="<?=(int)$w['id']?>" <?=$sw===(int)$w['id']?'selected':''?>><?=issueEscape($w['warehouse_name'])?></option><?php endforeach;?></select></div>
<div class="col-md-4"><label>درخواست‌کننده</label><input type="number" class="form-control" name="requested_by" value="<?=issueEscape($_POST['requested_by']??$voucher['requested_by']??'')?>"></div><div class="col-md-4"><label>تأییدکننده</label><input type="number" class="form-control" name="approved_by" value="<?=issueEscape($_POST['approved_by']??$voucher['approved_by']??'')?>"></div><div class="col-md-4"><label>وضعیت</label><select class="form-select" name="status"><?php $st=$_POST['status']??$voucher['status'];foreach(['draft'=>'پیش‌نویس','approved'=>'تأییدشده','issued'=>'خروج‌شده','cancelled'=>'لغوشده'] as $k=>$v):?><option value="<?=$k?>" <?=$st===$k?'selected':''?>><?=$v?></option><?php endforeach;?></select></div><div class="col-12"><label>توضیحات</label><textarea class="form-control" name="description"><?=issueEscape($_POST['description']??$voucher['description']??'')?></textarea></div></div>
<div class="table-responsive"><table class="table table-bordered" id="items"><thead><tr><th>کالا</th><th>تعداد</th><th>واحد</th><th>قیمت</th><th>سریال</th><th>Batch</th><th>انقضا</th><th>لوکیشن</th><th>توضیح</th><th></th></tr></thead><tbody><?php foreach(array_values($items) as $i=>$it):?><tr><td><select name="items[<?=$i?>][item_id]" class="form-select" required><?php foreach($products as $p):?><option value="<?=(int)$p['id']?>" data-price="<?=issueEscape($p['price'])?>" <?=(int)($it['item_id']??0)===(int)$p['id']?'selected':''?>><?=issueEscape($p['title'])?></option><?php endforeach;?></select></td><td><input type="number" step=".001" min=".001" class="form-control" name="items[<?=$i?>][quantity]" value="<?=issueEscape($it['quantity']??'')?>" required></td><td><input class="form-control" name="items[<?=$i?>][unit]" value="<?=issueEscape($it['unit']??'piece')?>"></td><td><input type="number" step=".01" class="form-control" name="items[<?=$i?>][unit_cost]" value="<?=issueEscape($it['unit_cost']??0)?>"></td><td><input class="form-control" name="items[<?=$i?>][serial_number]" value="<?=issueEscape($it['serial_number']??'')?>"></td><td><input class="form-control" name="items[<?=$i?>][batch_number]" value="<?=issueEscape($it['batch_number']??'')?>"></td><td><input type="date" class="form-control" name="items[<?=$i?>][expire_date]" value="<?=issueEscape($it['expire_date']??'')?>"></td><td><input class="form-control" name="items[<?=$i?>][warehouse_location]" value="<?=issueEscape($it['warehouse_location']??'')?>"></td><td><input class="form-control" name="items[<?=$i?>][description]" value="<?=issueEscape($it['description']??'')?>"></td><td><button type="button" class="btn btn-danger btn-sm" onclick="this.closest('tr').remove()">×</button></td></tr><?php endforeach;?></tbody></table></div><button type="button" class="btn btn-outline-primary" onclick="addRow()">افزودن ردیف</button> <button class="btn btn-success">ذخیره تغییرات</button></form></div></div>
<script>let n=document.querySelectorAll('#items tbody tr').length;function addRow(){let r=document.querySelector('#items tbody tr').cloneNode(true);r.querySelectorAll('input').forEach(x=>x.value='');r.querySelectorAll('[name]').forEach(x=>x.name=x.name.replace(/\[\d+\]/,'['+(n++)+']'));document.querySelector('#items tbody').appendChild(r)}</script>
<?php endif;?>
